"""Obsidian MCP integration wrapper."""

from pathlib import Path
from typing import Optional, List, Dict, Any
from datetime import datetime

from ..config.settings import settings


class ObsidianClient:
    """
    Wrapper for Obsidian MCP operations.

    Saves research artifacts to Obsidian vault for user review and annotation.
    """

    def __init__(self, vault_path: Optional[Path] = None):
        """
        Initialize Obsidian client.

        Args:
            vault_path: Path to Obsidian vault (defaults to settings)
        """
        self.vault_path = vault_path or settings.obsidian_vault_path
        self.vault_path.mkdir(parents=True, exist_ok=True)

    def save_paper_summary(
        self,
        paper_id: str,
        title: str,
        authors: List[str],
        abstract: str,
        relevance_score: float,
        key_findings: Optional[str] = None
    ) -> Path:
        """
        Save paper summary to Obsidian vault.

        Args:
            paper_id: Paper identifier
            title: Paper title
            authors: List of authors
            abstract: Abstract
            relevance_score: Relevance score (0-10)
            key_findings: Key findings from analysis

        Returns:
            Path to created note
        """
        # Create Papers directory
        papers_dir = self.vault_path / "Papers"
        papers_dir.mkdir(exist_ok=True)

        # Sanitize filename
        safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '-', '_'))[:100]
        filename = f"{safe_title}.md"
        file_path = papers_dir / filename

        # Format content
        content = f"""# {title}

**Paper ID**: {paper_id}
**Authors**: {", ".join(authors)}
**Relevance Score**: {relevance_score:.1f}/10
**Added**: {datetime.now().strftime("%Y-%m-%d %H:%M")}

## Abstract

{abstract}
"""

        if key_findings:
            content += f"""

## Key Findings

{key_findings}
"""

        content += """

## Notes

<!-- Add your notes here -->

---
*Generated by AI Research System*
"""

        # Save to vault (via MCP in actual execution)
        # obsidian_update_note({
        #     "targetType": "filePath",
        #     "targetIdentifier": str(file_path.relative_to(self.vault_path)),
        #     "content": content,
        #     "modificationType": "wholeFile",
        #     "wholeFileMode": "overwrite"
        # })

        file_path.write_text(content)
        return file_path

    def save_research_ideas(
        self,
        project_id: str,
        domain: str,
        ideas: List[Dict[str, Any]],
        gaps_analysis: Optional[str] = None
    ) -> Path:
        """
        Save generated research ideas to Obsidian.

        Args:
            project_id: Project identifier
            domain: Research domain
            ideas: List of scored idea dictionaries
            gaps_analysis: Research gaps analysis text

        Returns:
            Path to created note
        """
        ideas_dir = self.vault_path / "Ideas"
        ideas_dir.mkdir(exist_ok=True)

        # Sanitize project_id for filename
        safe_project = "".join(c for c in project_id if c.isalnum() or c in ('-', '_'))
        filename = f"{safe_project}_ideas_{datetime.now().strftime('%Y%m%d')}.md"
        file_path = ideas_dir / filename

        content = f"""# Research Ideas: {project_id}

**Domain**: {domain}
**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Total Ideas**: {len(ideas)}

---

"""

        # Add gaps analysis if provided
        if gaps_analysis:
            content += f"""## Research Gaps Analysis

{gaps_analysis}

---

"""

        # Add ideas with full details
        content += f"""## Generated Ideas

Ranked by overall score (Novelty × 0.35 + Feasibility × 0.35 + Impact × 0.30)

"""

        for i, idea in enumerate(ideas, 1):
            overall = idea.get('overall_score', 0)
            novelty = idea.get('novelty_score', 0)
            feasibility = idea.get('feasibility_score', 0)
            impact = idea.get('impact_score', 0)

            content += f"""### {i}. {idea.get('title', 'Untitled')}

**Overall Score**: {overall:.2f}/10 | **Novelty**: {novelty:.1f} | **Feasibility**: {feasibility:.1f} | **Impact**: {impact:.1f}

#### Description
{idea.get('description', 'No description provided')}

#### Approach
{idea.get('approach', 'No approach specified')}

#### Why Novel?
{idea.get('why_novel', 'Novelty not specified')}

#### Potential Impact
{idea.get('potential_impact', 'Impact not specified')}

#### Resources Needed
{idea.get('resources_needed', 'Resources not specified')}

#### Risks
{idea.get('risks', 'No risks identified')}

---

"""

        content += """
## Next Steps

1. Review each idea carefully
2. Discuss top ideas with domain experts
3. Select 1-2 ideas for hypothesis formation (Agent 3)
4. Consider resource availability before committing

---
*Generated by AI Research System - Agent 2: Idea Generation*
"""

        file_path.write_text(content)
        return file_path

    def save_hypothesis(
        self,
        hypothesis_id: str,
        project_id: str,
        idea_title: str,
        hypothesis_text: str,
        null_hypothesis: Optional[str],
        variables: Dict[str, List[str]],
        success_criteria: Dict[str, Any]
    ) -> Path:
        """
        Save hypothesis to Obsidian vault.

        Args:
            hypothesis_id: Hypothesis identifier
            project_id: Project identifier
            idea_title: Original idea title
            hypothesis_text: The hypothesis statement
            null_hypothesis: Null hypothesis statement
            variables: Dict with independent, dependent, control variables
            success_criteria: Success criteria dict

        Returns:
            Path to created note
        """
        hypotheses_dir = self.vault_path / "Hypotheses"
        hypotheses_dir.mkdir(exist_ok=True)

        # Sanitize for filename
        safe_title = "".join(c for c in idea_title if c.isalnum() or c in (' ', '-', '_'))[:80]
        filename = f"{safe_title}_{hypothesis_id[:8]}.md"
        file_path = hypotheses_dir / filename

        content = f"""# Hypothesis: {idea_title}

**Hypothesis ID**: {hypothesis_id}
**Project**: {project_id}
**Created**: {datetime.now().strftime("%Y-%m-%d %H:%M")}

---

## Hypothesis Statement (H1)

{hypothesis_text}

## Null Hypothesis (H0)

{null_hypothesis or "Not specified"}

---

## Variables

### Independent Variables (What we manipulate)
{self._format_list(variables.get('independent', []))}

### Dependent Variables (What we measure)
{self._format_list(variables.get('dependent', []))}

### Control Variables (What we keep constant)
{self._format_list(variables.get('control', []))}

---

## Success Criteria

- **Statistical Significance**: p < {success_criteria.get('significance_level', 0.05)}
- **Minimum Effect Size**: {success_criteria.get('minimum_effect_size', 0.3)}
- **Minimum Sample Size**: {success_criteria.get('minimum_sample_size', 100)}

### Metrics
{self._format_dict(success_criteria.get('metrics', {}))}

---

## Next Steps

1. Review and validate hypothesis
2. Ensure variables are measurable
3. Run Agent 4 to design experiments
4. Consider ethical implications

---
*Generated by AI Research System - Agent 3: Hypothesis Formation*
"""

        file_path.write_text(content)
        return file_path

    def _format_list(self, items: List[str]) -> str:
        """Format list as markdown bullets."""
        if not items:
            return "- (None specified)"
        return "\n".join([f"- {item}" for item in items])

    def _format_dict(self, d: Dict[str, Any]) -> str:
        """Format dict as markdown list."""
        if not d:
            return "- (None specified)"
        return "\n".join([f"- **{k}**: {v}" for k, v in d.items()])

    def save_experiment_design(
        self,
        design_id: str,
        hypothesis_text: str,
        methodology: str,
        data_requirements: Dict[str, Any],
        code_template: str,
        resources: Dict[str, Any]
    ) -> Path:
        """Save experiment design to Obsidian vault."""
        designs_dir = self.vault_path / "Experiment_Designs"
        designs_dir.mkdir(exist_ok=True)

        filename = f"design_{design_id[:12]}.md"
        file_path = designs_dir / filename

        content = f"""# Experiment Design: {design_id}

**Created**: {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Hypothesis**: {hypothesis_text[:100]}...

---

## Methodology

{methodology}

---

## Data Requirements

- **Source**: {data_requirements.get('dataset_source', 'N/A')}
- **Min Samples**: {data_requirements.get('min_samples', 'N/A')}
- **Format**: {data_requirements.get('data_format', 'N/A')}

### Required Features
{self._format_list(data_requirements.get('required_features', []))}

---

## Resource Estimates

- **Compute Time**: {resources.get('estimated_compute_time', 'N/A')}
- **Cost**: ${resources.get('estimated_cost_usd', 0):.2f}
- **Platform**: {resources.get('platform', 'local')}
- **Memory**: {resources.get('memory_gb', 'N/A')} GB
- **Storage**: {resources.get('storage_gb', 'N/A')} GB

---

## Code Template

```python
{code_template}
```

---

## Next Steps

1. Review and customize code template
2. Prepare data source
3. Run Agent 5 to execute experiment
4. Monitor resource usage

---
*Generated by AI Research System - Agent 4: Experiment Design*
"""

        file_path.write_text(content)
        return file_path

    def save_experiment_results(
        self,
        project_name: str,
        experiment_id: str,
        results: Dict[str, Any]
    ) -> Path:
        """
        Save experiment results to Obsidian.

        Args:
            project_name: Project name
            experiment_id: Experiment identifier
            results: Results dictionary

        Returns:
            Path to created note
        """
        experiments_dir = self.vault_path / "Experiments"
        experiments_dir.mkdir(exist_ok=True)

        filename = f"{project_name}_{experiment_id}.md"
        file_path = experiments_dir / filename

        content = f"""# Experiment: {experiment_id}

**Project**: {project_name}
**Date**: {datetime.now().strftime("%Y-%m-%d %H:%M")}

## Results

```json
{results}
```

## Analysis

<!-- AI-generated analysis will appear here -->

## Notes

<!-- Add your notes here -->

---
*Generated by AI Research System*
"""

        file_path.write_text(content)
        return file_path

    def save_analysis(
        self,
        analysis_id: str,
        hypothesis_text: str,
        decision: str,
        statistical_results: Dict[str, Any],
        insights: str,
        metrics: Dict[str, Any]
    ) -> Path:
        """
        Save analysis results to Obsidian vault.

        Args:
            analysis_id: Analysis identifier
            hypothesis_text: The hypothesis that was tested
            decision: Decision about hypothesis (ACCEPT/REJECT/INCONCLUSIVE)
            statistical_results: Dict with p_value, effect_size, etc.
            insights: AI-generated insights text
            metrics: Experimental metrics dictionary

        Returns:
            Path to created note
        """
        analyses_dir = self.vault_path / "Analyses"
        analyses_dir.mkdir(exist_ok=True)

        # Sanitize hypothesis for filename
        safe_title = "".join(c for c in hypothesis_text if c.isalnum() or c in (' ', '-', '_'))[:60]
        filename = f"{safe_title}_{analysis_id[:8]}.md"
        file_path = analyses_dir / filename

        # Format statistical results
        p_value = statistical_results.get("p_value", "N/A")
        effect_size = statistical_results.get("effect_size", "N/A")
        ci = statistical_results.get("confidence_interval", {})
        ci_lower = ci.get("lower", "N/A") if isinstance(ci, dict) else "N/A"
        ci_upper = ci.get("upper", "N/A") if isinstance(ci, dict) else "N/A"
        sample_size = statistical_results.get("sample_size", "N/A")
        sig_level = statistical_results.get("significance_level", 0.05)
        is_significant = statistical_results.get("statistically_significant", False)

        # Format metrics
        metrics_str = self._format_dict(metrics) if metrics else "- No metrics available"

        content = f"""# Analysis: {hypothesis_text[:80]}

**Analysis ID**: {analysis_id}
**Date**: {datetime.now().strftime("%Y-%m-%d %H:%M")}

---

## Decision

**{decision}**

---

## Statistical Results

- **P-value**: {p_value if isinstance(p_value, str) else f"{p_value:.4f}"}
- **Significance Level**: {sig_level}
- **Statistically Significant**: {"Yes" if is_significant else "No"}
- **Effect Size**: {effect_size if isinstance(effect_size, str) else f"{effect_size:.3f}"}
- **Confidence Interval**: [{ci_lower if isinstance(ci_lower, str) else f"{ci_lower:.3f}"}, {ci_upper if isinstance(ci_upper, str) else f"{ci_upper:.3f}"}]
- **Sample Size**: {sample_size}

### Interpretation

- **P-value** measures the probability of seeing these results if the null hypothesis were true
  - p < {sig_level} indicates statistical significance
  - Your result: {"Significant" if is_significant else "Not significant"}

- **Effect Size** measures the magnitude of the difference/relationship
  - < 0.2 = small effect
  - 0.2-0.5 = medium effect
  - > 0.5 = large effect

---

## Experimental Metrics

{metrics_str}

---

## Insights

{insights}

---

## Next Steps

1. Review the decision and statistical evidence
2. Consider practical significance vs. statistical significance
3. Identify limitations of the study
4. Plan follow-up research if needed
5. Document findings for publication or application

---

## Notes

<!-- Add your interpretation and notes here -->

---
*Generated by AI Research System - Agent 6: Results Analysis*
"""

        file_path.write_text(content)
        return file_path
